### ISSUE TITLE
运行四人赛时报错

### ISSUE THREAD

**Issue by enterlet** [dundunnp/auto_xuexiqiangguo#281]
运行四人赛时报错，脚本就结束了
qg是2.33 hamibot是1.3.1
22:12:08.580/E: Wrapped java.lang.IllegalArgumentException: height must be > 0 (62444c18456a8235d7cb2fb8.js#1191)
Wrapped java.lang.IllegalArgumentException: height must be > 0
    at do_contest (62444c18456a8235d7cb2fb8.js:1191:0)
    at 62444c18456a8235d7cb2fb8.js:1233:0

**Comment by dundunnp** [comment]
每次执行脚本都会这样吗

**Comment by enterlet** [comment]
试了几次，不重启手机的话，第二天基本上可以肯定会出现这个错误

**Comment by enterlet** [comment]
试了几次，不重启手机的话，第二天基本上可以肯定会出现这个错误

**Comment by lavengu** [comment]
> 每次执行脚本都会这样吗

我也每次都会出现这个bug，求问解决了吗？谢谢！

**Comment by zxj1009587922** [comment]
我也出现了这样子的问题，解决了吗
