### ISSUE TITLE
haminot运行出错

### ISSUE THREAD

**Issue by isaenter** [dundunnp/auto_xuexiqiangguo#317]
14:50:59.760/E: Cannot convert NaN to java.lang.Long (file:///android_asset/modules/__globals__.js#16)
Cannot convert NaN to java.lang.Long
    at file:///android_asset/modules/__globals__.js:16:0

**Comment by Dazmk** [comment]
+1

> 14:50:59.760/E: Cannot convert NaN to java.lang.Long (file:///android_asset/modules/**globals**.js#16) Cannot convert NaN to java.lang.Long at file:///android_asset/modules/**globals**.js:16:0
