### ISSUE TITLE
更新后Can't find method 错误

### ISSUE THREAD

**Issue by Jone2008** [dundunnp/auto_xuexiqiangguo#347]
15:28:22.308/E: Can't find method com.stardust.autojs.runtime.api.Timers.clearInterval(org.mozilla.javascript.Undefined). (<init>#30)
Can't find method com.stardust.autojs.runtime.api.Timers.clearInterval(org.mozilla.javascript.Undefined).
    at <init>:30:0
    at /storage/emulated/0/脚本/xuexi.js:1240:0

**Comment by Jone2008** [comment]
Hamibot：

15:35:34.580/E: Can't find method com.stardust.autojs.runtime.api.Timers.clearInterval(org.mozilla.javascript.Undefined). (<init>#29)
Can't find method com.stardust.autojs.runtime.api.Timers.clearInterval(org.mozilla.javascript.Undefined).
    at <init>:29:0
    at **.js:1412:0
