### ISSUE TITLE
四人双人:13:43:21.468/E:TypeError:Cannot call method "bounds" of null (61f0****dd0c.js#1041) TypeError:Cannot call method "bounds" of null at handling_access_exceptions (61f0****dd0c.js:1041:0) at do_contest (61f0****dd0c.js:1295:0) at 61f0****dd0c.js:1361:0

### ISSUE THREAD

**Issue by Watson0635** [dundunnp/auto_xuexiqiangguo#367]
13:43:21.468/E:TypeError:Cannot
call method "bounds" of null
(61f0****dd0c.js#1041)
TypeError:Cannot call method "bounds" of null
at handling_access_exceptions
(61f0****dd0c.js:1041:0)
at do_contest (61f0****dd0c.js:1295:0)
at 61f0****dd0c.js:1361:0

**Comment by zhmoffice** [comment]
马一个，同样的问题

**Comment by zhmoffice** [comment]
> 13:43:21.468/E:TypeError:Cannot call method "bounds" of null (61f0****dd0c.js#1041) TypeError:Cannot call method "bounds" of null at handling_access_exceptions (61f0****dd0c.js:1041:0) at do_contest (61f0****dd0c.js:1295:0) at 61f0****dd0c.js:1361:0

终于找到问题了，可能就是布局不同，现在的1041行代码： var pos = className('android.view.View').depth(10).clickable(true).findOnce(1).bounds();
把其“findOnce(1)”改成"findOnce(0)"，你试试你的
