### ISSUE TITLE
第一次尝试配置还是报错 有大佬能帮我看看报错原因是什么吗

### ISSUE THREAD

**Issue by chouhetang** [dundunnp/auto_xuexiqiangguo#420]
17:33:58.753/E: SyntaxError: JSON.parse (file:///android_asset/modules/__json2__.js#505)
SyntaxError: JSON.parse
    at file:///android_asset/modules/__json2__.js:505:0
    at 62a0590e3efee7bcbf2ffe58.js:142:0

**Comment by coffeetang-haitao** [comment]
一样的情况，app版本233，手机是pixel xl，系统Android11
