### ISSUE TITLE
大佬们刚运行就结束是怎么个情况啊哭泣。附错误代码。

### ISSUE THREAD

**Issue by YaoYaoYaYi** [dundunnp/auto_xuexiqiangguo#438]
01:34:14.675/V:开始运行[/storage/emulated/0/脚本/学习强国.js]
01:34:20.368/E: Wrapped okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR (file:///android_asset/modules/http_.js#49)
Wrapped okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
at file:///android_asset/modules/_http_.js:49:0
at /storage/emulated/0/脚本/习强.js:113:0
[/storage/emulated/0/脚本/学习强国.js]运行结束,用时5.694000秒

**Comment by Borzzj** [comment]
我也是刚运行就结束了，求解！
![错误提示](https://user-images.githubusercontent.com/84000044/174508191-a13dd0d7-7147-4f90-843c-2cc9fc45c56d.jpg)

**Comment by raulwang02** [comment]
我也是今天遇到该问题，之前一直可以正常使用，版本为1.31和2.33，将hamibot升级到1.4.2也不行。求解答，谢谢。

**Comment by okziji** [comment]
原因是github加速器用不了了，下载不了题库

**Comment by Borzzj** [comment]
> 所以有没有解决办法呢？

**Comment by hiwasax** [comment]
> 楼主你这字体花里胡哨的。。。。这OCR也比较耗时间，而且错误率也比较大啊

哈哈，是的。

**Comment by okziji** [comment]
github加速服务换成https://git.metauniverse-cn.com 感谢@[Jone2008](https://github.com/Jone2008)

**Comment by Jone2008** [comment]
> github加速服务换成https://git.metauniverse-cn.com 感谢@[Jone2008](https://github.com/Jone2008)

不客气，这个比较稳定，一直在用

**Comment by Jone2008** [comment]
> github加速服务换成https://git.metauniverse-cn.com 感谢@[Jone2008](https://github.com/Jone2008)

不客气，这个还挺稳定的，一直在用

**Comment by okziji** [comment]
> 问题解决了谢谢你@okziji

客气了，借花献佛

**Comment by YaoYaoYaYi** [comment]
问题解决了！谢谢！！ @okziji @Jone2008

**Comment by Jone2008** [comment]
如果有弹错误，把题库前缀更换一下。
或者直接 
https://gh-proxy.com/https://raw.githubusercontent.com/Mondayfirst/XXQG_TiKu/main/%E9%A2%98%E5%BA%93_%E6%8E%92%E5%BA%8F%E7%89%88.json
