### ISSUE TITLE
手机已经root但是无法冻结app，请大佬看看

### ISSUE THREAD

**Issue by sidfjsl** [dundunnp/auto_xuexiqiangguo#507]
> 23:41:43.556/E: Can't find method com.stardust.autojs.runtime.ScriptRuntime.exit(number). (6319f63e166a049949d66963.js#82)
Can't find method com.stardust.autojs.runtime.ScriptRuntime.exit(number).
    at check_set_env (6319f63e166a049949d66963.js:82:0)
    at 6319f63e166a049949d66963.js:93:0
![4E4DDE0245958BBBDBC04F622DDF50DC](https://user-images.githubusercontent.com/102895293/189171452-25ce09ce-99af-4c41-9a3e-c585dad33aa5.jpg)
![4E4DDE0245958BBBDBC04F622DDF50DC](https://user-images.githubusercontent.com/102895293/189171483-2bd28a16-670b-4dab-99ea-dec353da1e13.jpg)

**Comment by dundunnp** [comment]
因为我的手机没root，我也不好调试。解决方法是取消冻结app

**Comment by sidfjsl** [comment]
好的感谢作者回复
