### ISSUE TITLE
这是什么意思，新手，刚配置完百度智能云

### ISSUE THREAD

**Issue by iduncn** [dundunnp/auto_xuexiqiangguo#516]
20:39:22.305/E: SyntaxError: syntax error (file:///android_asset/modules/__json2__.js#493(eval)#1)
SyntaxError: syntax error
    at file:///android_asset/modules/__json2__.js:493:0
    at /storage/emulated/0/脚本/new强国.js:150:0

**Comment by klcb2010** [comment]
用机器人 不要用JS

**Comment by iduncn** [comment]
好的，我试试
