### ISSUE TITLE
脚本无法执行了，log如下@McMug2020

### ISSUE THREAD

**Issue by BigFireDog** [dundunnp/auto_xuexiqiangguo#549]
21:15:43.603/D: 新主脚本正在运行
21:15:45.394/E: SyntaxError: JSON.parse (file:///android_asset/modules/__json2__.js#505)
SyntaxError: JSON.parse
    at file:///android_asset/modules/__json2__.js:505:0
    at 62432a8a456a8235d7ca86b1.js:68:0

**Comment by McMug2020** [comment]
题库存放网盘挂了待修复

**Comment by McMug2020** [comment]
希望各位墩友能提供下能稳定大量访问的加速链接，谢谢😊

**Comment by Vagex** [comment]
题库可否改为 可自行修改设置

**Comment by McMug2020** [comment]
该问题已修复，请更新在线脚本🎈

**Comment by noobCoode** [comment]
在线脚本指的是哪个脚本呢。。

**Comment by McMug2020** [comment]
> 在线脚本指的是哪个脚本呢。。

https://hamibot.com/marketplace/gtf52?invite=ADfZFZnW31U9Xrnu7xy8Ns3U

**Comment by McMug2020** [comment]
> 题库可否改为 可自行修改设置 毕竟这个可能会遭到举报被堵，让个人自行设置的话，可以缓解访问压力

可自行复制代码，替换题库文件加速链接运行

**Comment by 2592199042** [comment]
@McMug2020 网盘的地址能分享一个吗，谢谢。可以的话修改一下https://github.com/McMug2020/hamibot-auto_xuexiqiangguo/blob/main/%E5%9B%9B%E4%BA%BA%E8%B5%9B%E5%8F%8C%E4%BA%BA%E5%AF%B9%E6%88%98/%E5%9B%9B%E4%BA%BA%E8%B5%9B%E5%8F%8C%E4%BA%BA%E5%AF%B9%E6%88%98.js

**Comment by McMug2020** [comment]
@2592199042 已更新请查阅，请查看更新的内容以便失效后替换https://github.com/McMug2020/hamibot-auto_xuexiqiangguo/commit/c28c7db73952e6c95a99771fe9a03b91889a63db
