### ISSUE TITLE
四人赛和双人赛单独对战脚本无法运行，求解#505 错误

### ISSUE THREAD

**Issue by sntyuxi** [dundunnp/auto_xuexiqiangguo#554]
15:18:47.398/:开始运行
「63563bf7848b2ce083edb765.js」
15:18:54.653/E:SyntaxError:JSON.parse
(file:///android_asset/modules/__json2_.js#505)
SyntaxError:JSON.parse
at file:///android_asset/modules/__json2_.js:505:0
at map_update (63563bf7848b2ce083edb765.js:187:0)
at63563bf7848b2ce083edb765.js:209:0
15:18:54.654/:「63563bf7848b2ce083edb765.js」运行结
束，用时7.256000秒

hamibot脚本 autox脚本 都是无法正常运行。

**Comment by frodo1984** [comment]
hami里面不要用McMug的json,用dundunnp的 换一个加速就行

**Comment by JerryLiuQD** [comment]
> hami里面不要用McMug的json,用dundunnp的 换一个加速就行

请问怎么换啊，没太明白。
