### ISSUE TITLE
Hamibot上双人和四人答题会提前结束脚本

### ISSUE THREAD

**Issue by ShuoHuangTesting** [dundunnp/auto_xuexiqiangguo#663]
不确定是我机器问题还是什么。

换了新版之后，进入双人或者四人答题不会答题，并且会直接结束脚本。

在更新当当前这个新版进度条修改之前没问题。

**Comment by dundunnp** [comment]
有什么报错信息吗

**Comment by ShuoHuangTesting** [comment]
> 有什么报错信息吗

21:10:46.054/E: Wrapped java.lang.IllegalArgumentException: height must be > 0 (63faed48745fd6bdf0013762.js#1497)
Wrapped java.lang.IllegalArgumentException: height must be > 0
    at do_contest (63faed48745fd6bdf0013762.js:1497:0)
    at 63faed48745fd6bdf0013762.js:1607:0

就是出现在双人或者四人对战loading的界面，机器是小米k30 miui 13.03

**Comment by zhufscug** [comment]
> 

作者回复过了，MIUI13支持不了，要用MIUI 12

**Comment by ShuoHuangTesting** [comment]
> 作者回复过了，MIUI13支持不了，要用MIUI 12

可以退回到上个版本吗？在新的验证码之前还都正常的，除了验证码卡住。反正现在也是卡住，不如退回之前。
