### ISSUE TITLE
求助auto

### ISSUE THREAD

**Issue by stand6324** [dundunnp/auto_xuexiqiangguo#676]
![Screenshot_2023-03-08-11-15-52-128_org autojs autojs](https://user-images.githubusercontent.com/88222865/223611179-a319db93-3f50-44f9-826f-ed1a4bbb0dfe.jpg)
这个是怎么回事啊

**Comment by stand6324** [comment]
重新弄了一遍还是不行

**Comment by stand6324** [comment]
11:33:03.720/E: Wrapped javax.net.ssl.SSLHandshakeException: Chain validation failed (file:///android_asset/modules/__http__.js#49)
Wrapped javax.net.ssl.SSLHandshakeException: Chain validation failed
    at file:///android_asset/modules/__http__.js:49:0
    at map_update (/storage/emulated/0/脚本/学习！.js:227:0)
    at /storage/emulated/0/脚本/学习！.js:251:0

**Comment by emmwdc** [comment]
我也是

**Comment by klcb2010** [comment]
脚本废了

**Comment by emmwdc** [comment]
好像是加速器到期了

**Comment by pananniyanjie** [comment]
我也是，提示下载题库就没反应了
