### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by bignoob231** [dundunnp/auto_xuexiqiangguo#690]
15:15:25.712/E: Wrapped java.lang.IllegalArgumentException: height must be > 0 (63f9be7ee9b29510e1634302.js#1457)
Wrapped java.lang.IllegalArgumentException: height must be > 0
    at do_contest (63f9be7ee9b29510e1634302.js:1457:0)
    at 63f9be7ee9b29510e1634302.js:1495:0

**Comment by bignoob231** [comment]
![image](https://user-images.githubusercontent.com/89678164/225399497-3765255a-a3f5-4de2-928f-1a54bb917cc7.png)
